title: Ekavanya U. Widodo # your name (or website title) here
logo: "/images/foto1.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate Student
  <br><br>
  MSIB Zenius
  <br><br>
  <a href="https://www.linkedin.com/in/ekavanya-utami/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
